Development abstraction class cli demo
GDP-ADMIN/zkpass-sdk pull request #45
Opened 2023-12-21 00:17 UTC by pp-pal

- Add abstraction class for cli demo

2024-01-02 09:55 UTC, LawrencePatrickSianto commented on typescript/node-js/cli/src/index.ts
>    ISSUER_JKU,
remove unused imports

2024-01-02 10:40 UTC, zulamdat commented on typescript/node-js/cli/src/libs/Holder.ts
> +    console.log("\n#### starting zkpass proof generation...");
@pp-pal ini bisa diganti sih lognya, soalnya sekarang double sama yg ada di MyHolder

2024-01-02 10:41 UTC, zulamdat approved these changes

2024-01-04 08:13 UTC, ntejapermana requested changes

2024-01-04 08:13 UTC, ntejapermana commented on typescript/node-js/cli/src/libs/Holder.ts
> +  }
Tambahin satu abstract function 
`public async start(
     userDataToken: string,
     dvrToken: string,
     zkPassServiceUrl: string,
     apiKey: ZkPassApiKey
   ): Promise<string>`

2024-01-04 08:13 UTC, ntejapermana commented on typescript/node-js/cli/src/libs/Issuer.ts
> +}
tambahin abstract function 
`public async getUserDataToken(dataFile: string): Promise<string>`

2024-01-04 08:13 UTC, ntejapermana commented on typescript/node-js/cli/src/libs/Verifier.ts
> +}
Tambahin abstract function:
`async getDvrToken(dvrFile: string): Promise<string>`

2024-01-04 08:23 UTC, LawrencePatrickSianto commented on typescript/node-js/cli/src/libs/Verifier.ts
> +}
done, please recheck

2024-01-04 08:23 UTC, LawrencePatrickSianto commented on typescript/node-js/cli/src/libs/Issuer.ts
> +}
done, please recheck

2024-01-04 08:23 UTC, LawrencePatrickSianto commented on typescript/node-js/cli/src/libs/Holder.ts
> +  }
done, please recheck

2024-01-08 06:37 UTC, ntejapermana approved these changes

2024-01-08 06:37 UTC, merged